package main

import (
	"os"
	"path/filepath"
	"testing"
)

func TestEvaluateDependencyLockContract(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "pyproject.toml", `[project]
dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.7",
  "mlflow>=2.14",
  "dvc[s3]>=3.50",
  "prometheus-client>=0.20",
  "opentelemetry-api>=1.25",
  "opentelemetry-sdk>=1.25",
  "evidently>=0.4",
]
[project.optional-dependencies]
ml = ["torch>=2.3", "transformers>=4.42", "accelerate>=0.31", "bitsandbytes>=0.43", "diffusers>=0.29"]
serving = ["vllm>=0.5"]
`)
	writeFixture(t, root, "uv.lock", uvLockFixture())
	writeFixture(t, root, "web/package.json", `{"name":"tryops-console","dependencies":{"react":"^18.3.1"},"devDependencies":{"vite":"^8.0.16"}}`)
	writeFixture(t, root, "web/package-lock.json", `{"name":"tryops-console","lockfileVersion":3,"packages":{"":{"name":"tryops-console"},"node_modules/react":{"version":"18.3.1","integrity":"sha512-a"},"node_modules/vite":{"version":"8.0.16","integrity":"sha512-b"},"node_modules/transitive":{"version":"1.0.0","integrity":"sha512-c"}}}`)
	writeFixture(t, root, "native/rust/tryops-gateway/Cargo.toml", `[package]
name = "tryops-gateway"
[dependencies]
axum = "0.8"
tokio = "1"
serde = "1"
serde_json = "1"
sha2 = "0.10"
reqwest = "0.12"
rustls = "0.23"
tracing = "0.1"
`)
	writeFixture(t, root, "native/rust/tryops-gateway/Cargo.lock", cargoLockFixture())
	writeFixture(t, root, "native/go/one/go.mod", "module example.com/one\n\ngo 1.19\n\nrequire gopkg.in/yaml.v3 v3.0.1\n")
	writeFixture(t, root, "native/go/one/go.sum", "gopkg.in/yaml.v3 v3.0.1 h1:abc\n")
	writeFixture(t, root, "native/go/two/go.mod", "module example.com/two\n\ngo 1.19\n")
	writeFixture(t, root, "Makefile", "native-dependency-lock-contract-build:\n\tcd native/go/tryops-dependency-lock-contract && go build\nnative-dependency-lock-contract-test:\n\tcd native/go/tryops-dependency-lock-contract && go test ./...\nnative-dependency-lock-contract-sample:\n\tartifacts/native/tryops_dependency_lock_contract\nnative/go/tryops-dependency-lock-contract\nci: native-dependency-lock-contract-sample\n")

	report, err := evaluate(Config{
		RootPath:        root,
		PyprojectPath:   "pyproject.toml",
		UVLockPath:      "uv.lock",
		PackageJSONPath: "web/package.json",
		PackageLockPath: "web/package-lock.json",
		CargoTomlPath:   "native/rust/tryops-gateway/Cargo.toml",
		CargoLockPath:   "native/rust/tryops-gateway/Cargo.lock",
		GoRootPath:      "native/go",
		MakefilePath:    "Makefile",
		OutputPath:      "artifacts/eval/dependencies/native_dependency_lock_contract.json",
	})
	if err != nil {
		t.Fatal(err)
	}
	if !report.Passed || report.Summary.FailedChecks != 0 {
		t.Fatalf("expected passing report: %#v", report.Checks)
	}
	if report.Python.LockedPackageCount < 15 || report.Summary.GoModules != 2 || report.Summary.GoChecksumCoverage != 1 {
		t.Fatalf("unexpected summary: %#v", report.Summary)
	}
}

func TestGoChecksumCoverageFailsWhenSumMissing(t *testing.T) {
	root := t.TempDir()
	writeFixture(t, root, "native/go/one/go.mod", "module example.com/one\n\ngo 1.19\n\nrequire gopkg.in/yaml.v3 v3.0.1\n")
	cfg := Config{RootPath: root, GoRootPath: "native/go"}
	modules, checks := validateGoModules(cfg)
	if len(modules) != 1 {
		t.Fatalf("expected module summary: %#v", modules)
	}
	if allPassed(checks) {
		t.Fatalf("expected checksum failure: %#v", checks)
	}
}

func writeFixture(t *testing.T, root string, path string, body string) {
	t.Helper()
	full := filepath.Join(root, path)
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
}

func allPassed(checks []Check) bool {
	for _, check := range checks {
		if !check.Passed {
			return false
		}
	}
	return true
}

func uvLockFixture() string {
	names := []string{"fastapi", "uvicorn", "pydantic", "mlflow", "dvc", "prometheus-client", "opentelemetry-api", "opentelemetry-sdk", "evidently", "torch", "transformers", "accelerate", "bitsandbytes", "diffusers", "vllm", "transitive"}
	out := "version = 1\nrevision = 3\nrequires-python = \">=3.11\"\n"
	for _, name := range names {
		out += "\n[[package]]\nname = \"" + name + "\"\nversion = \"1.0.0\"\nsdist = { hash = \"sha256:abc\" }\nwheels = [{ hash = \"sha256:def\" }]\n"
	}
	return out
}

func cargoLockFixture() string {
	names := []string{"tryops-gateway", "axum", "tokio", "serde", "serde_json", "sha2", "reqwest", "rustls", "tracing", "transitive"}
	out := "# This file is automatically @generated by Cargo.\nversion = 4\n"
	for _, name := range names {
		out += "\n[[package]]\nname = \"" + name + "\"\nversion = \"1.0.0\"\nchecksum = \"abc\"\n"
	}
	return out
}
