package main

import (
	"fmt"
	"sort"
	"strings"
)

func validateRust(cfg Config) (RustSummary, []Check) {
	checks := []Check{}
	toml, err := readText(cfg.RootPath, cfg.CargoTomlPath)
	checks = append(checks, check("rust.cargo_toml.present", err == nil, cfg.CargoTomlPath))
	direct := []string{}
	if err == nil {
		direct = parseCargoTomlDependencies(toml)
		checks = append(checks, check("rust.direct_dependencies_declared", len(direct) >= 8, formatCount(len(direct))))
	}

	lock, err := readText(cfg.RootPath, cfg.CargoLockPath)
	checks = append(checks, check("rust.cargo_lock.present", err == nil, cfg.CargoLockPath))
	locked := map[string]bool{}
	checksumCount := 0
	if err == nil {
		locked, checksumCount = parseCargoLock(lock)
		checks = append(checks, check("rust.cargo_lock.generated", strings.Contains(lock, "automatically @generated by Cargo"), cfg.CargoLockPath))
		checks = append(checks, check("rust.cargo_lock.package_count", len(locked) > len(direct), formatCount(len(locked))))
		checks = append(checks, check("rust.cargo_lock.checksum_coverage", checksumCount > len(direct), formatCount(checksumCount)))
	}
	missing := []string{}
	for _, dep := range direct {
		if !locked[dep] {
			missing = append(missing, dep)
		}
	}
	checks = append(checks, check("rust.direct_dependencies_locked", len(missing) == 0 && len(direct) > 0, fmt.Sprintf("missing=%v", missing)))
	checks = append(checks, check("rust.gateway_binary_locked", locked["tryops-gateway"], "tryops-gateway"))

	return RustSummary{
		CargoTomlPath:      cfg.CargoTomlPath,
		CargoLockPath:      cfg.CargoLockPath,
		DirectDependencies: direct,
		LockedPackageCount: len(locked),
		ChecksumCount:      checksumCount,
	}, checks
}

func parseCargoTomlDependencies(text string) []string {
	inDeps := false
	out := []string{}
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if line == "[dependencies]" {
			inDeps = true
			continue
		}
		if inDeps && strings.HasPrefix(line, "[") {
			break
		}
		if !inDeps || line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		name := strings.TrimSpace(parts[0])
		if name != "" {
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out
}

func parseCargoLock(text string) (map[string]bool, int) {
	locked := map[string]bool{}
	checksumCount := 0
	for _, raw := range strings.Split(text, "\n") {
		line := strings.TrimSpace(raw)
		if strings.HasPrefix(line, "name = ") {
			locked[quotedValue(line)] = true
		}
		if strings.HasPrefix(line, "checksum = ") {
			checksumCount++
		}
	}
	return locked, checksumCount
}
