package main

import (
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"os"
	"path/filepath"
)

var (
	colorPage      = color.RGBA{R: 247, G: 248, B: 245, A: 255}
	colorPanel     = color.RGBA{R: 255, G: 255, B: 255, A: 255}
	colorPanelSoft = color.RGBA{R: 251, G: 252, B: 248, A: 255}
	colorInk       = color.RGBA{R: 32, G: 35, B: 31, A: 255}
	colorMuted     = color.RGBA{R: 101, G: 112, B: 95, A: 255}
	colorSidebar   = color.RGBA{R: 32, G: 35, B: 31, A: 255}
	colorAccent    = color.RGBA{R: 214, G: 240, B: 101, A: 255}
	colorGreen     = color.RGBA{R: 38, G: 133, B: 109, A: 255}
	colorBlue      = color.RGBA{R: 55, G: 120, B: 184, A: 255}
	colorAmber     = color.RGBA{R: 196, G: 135, B: 34, A: 255}
	colorRed       = color.RGBA{R: 189, G: 75, B: 68, A: 255}
	colorBorder    = color.RGBA{R: 220, G: 226, B: 214, A: 255}
)

func renderStoryboard(cfg config, board storyboard) ([]frameSummary, error) {
	if err := os.MkdirAll(cfg.FramesDir, 0o755); err != nil {
		return nil, err
	}
	if err := cleanFrameDir(cfg.FramesDir); err != nil {
		return nil, err
	}
	faces, err := loadFonts(cfg.FontPath)
	if err != nil {
		return nil, err
	}
	var frames []frameSummary
	write := func(img *image.RGBA, title string, kind string) error {
		index := len(frames) + 1
		path := filepath.Join(cfg.FramesDir, fmt.Sprintf("frame_%03d.png", index))
		if err := writePNG(path, img); err != nil {
			return err
		}
		frames = append(frames, frameSummary{
			Index: index,
			Path:  relPath(cfg.Root, path),
			Title: title,
			Kind:  kind,
		})
		return nil
	}
	if err := write(renderIntroFrame(cfg, faces, board), "Professor Demo Backup", "intro"); err != nil {
		return nil, err
	}
	for _, item := range board.Steps {
		if err := write(renderStepFrame(cfg, faces, item), item.Title, "step"); err != nil {
			return nil, err
		}
	}
	if err := write(renderCloseFrame(cfg, faces, board), "Evidence Bundle", "close"); err != nil {
		return nil, err
	}
	return frames, nil
}

func cleanFrameDir(dir string) error {
	matches, err := filepath.Glob(filepath.Join(dir, "frame_*.png"))
	if err != nil {
		return err
	}
	for _, path := range matches {
		if err := os.Remove(path); err != nil {
			return err
		}
	}
	return nil
}

func newCanvas(cfg config) *image.RGBA {
	img := image.NewRGBA(image.Rect(0, 0, cfg.Width, cfg.Height))
	fill(img, img.Bounds(), colorPage)
	fill(img, image.Rect(0, 0, 260, cfg.Height), colorSidebar)
	fill(img, image.Rect(28, 28, 70, 70), colorAccent)
	return img
}

func renderIntroFrame(cfg config, faces fonts, board storyboard) *image.RGBA {
	img := newCanvas(cfg)
	drawText(img, faces.H2, 84, 48, "TryOps Console", color.RGBA{R: 255, G: 255, B: 255, A: 255})
	drawText(img, faces.Small, 84, 68, "Enterprise AI operations", color.RGBA{R: 203, G: 215, B: 195, A: 255})
	drawText(img, faces.Title, 320, 92, "Professor Demo Backup", colorInk)
	drawWrapped(img, faces.Body, 320, 132, 760, 22, "Seeded, no-network, no-GPU walkthrough generated from the same JSON storyboard used by the Console.", colorMuted, 3)
	renderMetricCards(img, faces, 320, 195, board.Metrics)
	renderStatusStrip(img, faces, 320, 400, "Offline runbook", "This video is a backup artifact. The live Console view remains the primary demonstration path.", colorBlue)
	drawText(img, faces.Small, 320, 622, "Generated by native/go/tryops-demo-recorder with FFmpeg encoding.", colorMuted)
	return img
}

func renderStepFrame(cfg config, faces fonts, item step) *image.RGBA {
	img := newCanvas(cfg)
	renderSidebar(img, faces, item)
	drawText(img, faces.Small, 320, 50, "Seeded offline walkthrough", colorMuted)
	drawText(img, faces.Title, 320, 91, item.Title, colorInk)
	renderPill(img, faces, 1060, 58, item.Status, toneColor(item.Tone))
	drawWrapped(img, faces.Body, 320, 128, 760, 22, item.Summary, colorMuted, 3)
	renderMetricCards(img, faces, 320, 205, item.Metrics)
	renderStatusStrip(img, faces, 320, 348, item.Track, item.OperatorLine, toneColor(item.Tone))
	renderTranscript(img, faces, 320, 440, item.Transcript)
	renderCommandBox(img, faces, 840, 438, item)
	return img
}

func renderCloseFrame(cfg config, faces fonts, board storyboard) *image.RGBA {
	img := newCanvas(cfg)
	renderSidebarBase(img, faces)
	drawText(img, faces.Title, 320, 92, "Evidence Bundle", colorInk)
	drawWrapped(img, faces.Body, 320, 132, 760, 22, "The backup recording references the local artifacts that prove the same path: quota, safety gate, Pareto, energy, VTON quality, lineage, rollback, and governance.", colorMuted, 4)
	y := 220
	for _, item := range board.Steps {
		renderListRow(img, faces, 320, y, 790, item.Order, item.Title, item.PrimaryArtifact, toneColor(item.Tone))
		y += 54
	}
	return img
}

func renderSidebar(img *image.RGBA, faces fonts, item step) {
	renderSidebarBase(img, faces)
	y := 150
	nav := []string{"Dashboard", "Professor Demo", "LLM Playground", "VTON Studio", "Evaluations", "Incidents"}
	for _, label := range nav {
		rect := image.Rect(18, y-24, 242, y+14)
		if label == "Professor Demo" {
			fill(img, rect, color.RGBA{R: 55, G: 68, B: 46, A: 255})
			fill(img, image.Rect(18, y-24, 22, y+14), colorAccent)
		}
		drawText(img, faces.Small, 34, y, label, color.RGBA{R: 233, G: 239, B: 226, A: 255})
		y += 48
	}
	drawWrapped(img, faces.Small, 28, 605, 195, 18, "Native edge: Rust / Go / C++", color.RGBA{R: 203, G: 215, B: 195, A: 255}, 3)
	drawText(img, faces.Small, 28, 675, item.Order+" / 07", colorAccent)
}

func renderSidebarBase(img *image.RGBA, faces fonts) {
	drawText(img, faces.H2, 41, 57, "T", colorInk)
	drawText(img, faces.Body, 84, 48, "TryOps Console", color.RGBA{R: 255, G: 255, B: 255, A: 255})
	drawText(img, faces.Small, 84, 68, "Enterprise AI operations", color.RGBA{R: 203, G: 215, B: 195, A: 255})
}

func renderMetricCards(img *image.RGBA, faces fonts, x int, y int, metrics []metric) {
	for i, metric := range metrics {
		col := i % 4
		cardX := x + col*215
		rect := image.Rect(cardX, y, cardX+195, y+96)
		fill(img, rect, colorPanelSoft)
		stroke(img, rect, colorBorder)
		fill(img, image.Rect(cardX, y, cardX+5, y+96), toneColor(metric.Tone))
		drawText(img, faces.Small, cardX+16, y+28, metric.Label, colorMuted)
		drawWrapped(img, faces.H2, cardX+16, y+60, 160, 26, valueText(metric.Value), colorInk, 1)
		if metric.Detail != "" {
			drawWrapped(img, faces.Small, cardX+16, y+84, 160, 16, metric.Detail, colorMuted, 1)
		}
	}
}

func renderStatusStrip(img *image.RGBA, faces fonts, x int, y int, label string, body string, c color.Color) {
	rect := image.Rect(x, y, 1130, y+76)
	fill(img, rect, color.RGBA{R: 238, G: 250, B: 245, A: 255})
	stroke(img, rect, color.RGBA{R: 207, G: 226, B: 216, A: 255})
	fill(img, image.Rect(x, y, x+7, y+76), c)
	drawText(img, faces.Small, x+20, y+26, label, colorMuted)
	drawWrapped(img, faces.Body, x+20, y+52, 760, 20, body, colorInk, 2)
}

func renderTranscript(img *image.RGBA, faces fonts, x int, y int, lines []string) {
	for i, line := range lines {
		rowY := y + i*62
		renderTranscriptRow(img, faces, x, rowY, fmt.Sprintf("%02d", i+1), line)
	}
}

func renderTranscriptRow(img *image.RGBA, faces fonts, x int, y int, badge string, title string) {
	rect := image.Rect(x, y, x+500, y+54)
	fill(img, rect, colorPanelSoft)
	stroke(img, rect, colorBorder)
	fill(img, image.Rect(x+12, y+12, x+54, y+36), color.RGBA{R: 238, G: 250, B: 245, A: 255})
	drawText(img, faces.Small, x+22, y+29, badge, colorGreen)
	drawWrapped(img, faces.Small, x+68, y+20, 408, 15, title, colorInk, 3)
}

func renderCommandBox(img *image.RGBA, faces fonts, x int, y int, item step) {
	rect := image.Rect(x, y, 1175, y+212)
	fill(img, rect, colorInk)
	drawText(img, faces.Small, x+18, y+32, "COMMAND", color.RGBA{R: 203, G: 215, B: 195, A: 255})
	drawWrapped(img, faces.Mono, x+18, y+60, 290, 18, item.Command, color.RGBA{R: 255, G: 255, B: 255, A: 255}, 3)
	drawText(img, faces.Small, x+18, y+115, "PRIMARY ARTIFACT", color.RGBA{R: 203, G: 215, B: 195, A: 255})
	drawWrapped(img, faces.Mono, x+18, y+143, 290, 18, item.PrimaryArtifact, color.RGBA{R: 255, G: 255, B: 255, A: 255}, 4)
}

func renderListRow(img *image.RGBA, faces fonts, x int, y int, width int, badge string, title string, detail string, c color.Color) {
	rect := image.Rect(x, y, x+width, y+44)
	fill(img, rect, colorPanelSoft)
	stroke(img, rect, colorBorder)
	fill(img, image.Rect(x+12, y+10, x+54, y+34), color.RGBA{R: 238, G: 250, B: 245, A: 255})
	drawText(img, faces.Small, x+22, y+27, badge, c)
	textWidth := width - 88
	drawWrapped(img, faces.Body, x+68, y+27, textWidth, 19, title, colorInk, 1)
	if detail != "" {
		drawWrapped(img, faces.Small, x+68, y+42, textWidth, 16, detail, colorMuted, 1)
	}
}

func renderPill(img *image.RGBA, faces fonts, x int, y int, label string, c color.Color) {
	rect := image.Rect(x, y, x+100, y+30)
	fill(img, rect, colorPanelSoft)
	stroke(img, rect, c)
	drawText(img, faces.Small, x+14, y+21, label, c)
}

func toneColor(tone string) color.Color {
	switch tone {
	case "green":
		return colorGreen
	case "blue":
		return colorBlue
	case "amber":
		return colorAmber
	case "red":
		return colorRed
	default:
		return colorMuted
	}
}

func fill(img *image.RGBA, rect image.Rectangle, c color.Color) {
	draw.Draw(img, rect, image.NewUniform(c), image.Point{}, draw.Src)
}

func stroke(img *image.RGBA, rect image.Rectangle, c color.Color) {
	fill(img, image.Rect(rect.Min.X, rect.Min.Y, rect.Max.X, rect.Min.Y+1), c)
	fill(img, image.Rect(rect.Min.X, rect.Max.Y-1, rect.Max.X, rect.Max.Y), c)
	fill(img, image.Rect(rect.Min.X, rect.Min.Y, rect.Min.X+1, rect.Max.Y), c)
	fill(img, image.Rect(rect.Max.X-1, rect.Min.Y, rect.Max.X, rect.Max.Y), c)
}

func writePNG(path string, img image.Image) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	file, err := os.Create(path)
	if err != nil {
		return err
	}
	defer file.Close()
	return png.Encode(file, img)
}
