from __future__ import annotations

import json
import re
import shutil
import subprocess
import tomllib
from datetime import UTC, datetime
from hashlib import sha256
from importlib import metadata
from pathlib import Path
from typing import Any


LOCK_SCHEMA = "tryops.dependency_lock.v1"
SUPPLY_CHAIN_SCHEMA = "tryops.supply_chain_report.v1"
SPDX_SCHEMA = "SPDX-2.3"
DEFAULT_SUPPLY_CHAIN_DIR = Path("artifacts/eval/supply_chain")
REQUIREMENT_RE = re.compile(r"^\s*([A-Za-z0-9_.-]+)(\[[^\]]+\])?\s*(.*)$")
VERSION_RE = re.compile(r"(?:==|>=)\s*([A-Za-z0-9_.!+~-]+)")


def build_dependency_lock(pyproject_path: str | Path) -> dict[str, Any]:
    pyproject = tomllib.loads(Path(pyproject_path).read_text(encoding="utf-8"))
    project = dict(pyproject.get("project", {}))
    entries = []
    for requirement in project.get("dependencies", []):
        entries.append(_lock_requirement(requirement, group="project"))
    for group, requirements in sorted(project.get("optional-dependencies", {}).items()):
        for requirement in requirements:
            entries.append(_lock_requirement(requirement, group=str(group)))

    entries.sort(key=lambda item: (item["group"], item["name"], item["requirement"]))
    missing = [entry["name"] for entry in entries if not entry["installed"]]
    unpinned = [entry["requirement"] for entry in entries if not entry["locked_version"]]
    return {
        "schema_version": LOCK_SCHEMA,
        "created_at": datetime.now(UTC).isoformat(),
        "source": str(pyproject_path),
        "project": {
            "name": str(project.get("name", "")),
            "version": str(project.get("version", "")),
            "requires_python": str(project.get("requires-python", "")),
        },
        "dependencies": entries,
        "audit": {
            "dependency_count": len(entries),
            "missing_installed_distributions": sorted(missing),
            "unpinned_requirements": sorted(unpinned),
            "all_requirements_have_lock_version": not unpinned,
            "passed": bool(entries) and not unpinned,
        },
    }


def render_requirements_lock(lock: dict[str, Any]) -> str:
    lines = [
        "# Generated by scripts/generate_supply_chain_report.py",
        "# Direct project dependency lock for TryOps supply-chain evidence.",
        "# Missing optional/runtime packages are pinned to the lower bound declared in pyproject.toml.",
        "",
    ]
    for entry in lock["dependencies"]:
        package = entry["requirement_name"]
        version = entry["locked_version"]
        source = entry["lock_source"]
        group = entry["group"]
        requirement = entry["requirement"]
        lines.append(f"{package}=={version}  # group={group} source={source} requirement={requirement}")
    lines.append("")
    return "\n".join(lines)


def write_dependency_lock(
    *,
    pyproject_path: str | Path,
    requirements_output: str | Path,
    json_output: str | Path,
) -> dict[str, Any]:
    lock = build_dependency_lock(pyproject_path)
    requirements_path = Path(requirements_output)
    requirements_path.write_text(render_requirements_lock(lock), encoding="utf-8")
    json_path = Path(json_output)
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(lock, indent=2, sort_keys=True), encoding="utf-8")
    return lock


def load_model_sources(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_dataset_licenses(path: str | Path) -> dict[str, Any]:
    return json.loads(Path(path).read_text(encoding="utf-8"))


def audit_model_sources(payload: dict[str, Any]) -> dict[str, Any]:
    models = list(payload.get("models", []))
    missing = _missing_fields(models, ["id", "workload", "source_uri", "revision", "license", "status"])
    unknown_licenses = sorted(str(item.get("id", "")) for item in models if str(item.get("license", "")).lower() in {"", "unknown", "unverified"})
    return {
        "schema_version": "tryops.model_source_audit.v1",
        "model_count": len(models),
        "workloads": sorted({str(item.get("workload", "")) for item in models if item.get("workload")}),
        "missing_required_fields": missing,
        "unknown_license_models": unknown_licenses,
        "passed": bool(models) and not missing and not unknown_licenses,
    }


def audit_dataset_licenses(payload: dict[str, Any]) -> dict[str, Any]:
    datasets = list(payload.get("datasets", []))
    missing = _missing_fields(
        datasets,
        ["id", "source_uri", "license", "allowed_use", "access_status", "usage_restrictions"],
    )
    commercial_blocked = sorted(
        str(item.get("id", ""))
        for item in datasets
        if "commercial" in " ".join(str(value) for value in item.get("usage_restrictions", [])).lower()
    )
    return {
        "schema_version": "tryops.dataset_license_audit.v1",
        "dataset_count": len(datasets),
        "datasets_with_commercial_restrictions": commercial_blocked,
        "missing_required_fields": missing,
        "passed": bool(datasets) and not missing,
    }


def build_spdx_sbom(
    *,
    lock: dict[str, Any],
    model_sources: dict[str, Any],
    dataset_licenses: dict[str, Any],
    document_name: str = "tryops-local-supply-chain",
) -> dict[str, Any]:
    created_at = datetime.now(UTC).replace(microsecond=0).isoformat()
    packages = [_project_package(lock)]
    for entry in lock["dependencies"]:
        packages.append(_dependency_package(entry))
    for item in model_sources.get("models", []):
        packages.append(_source_package(item, category="model"))
    for item in dataset_licenses.get("datasets", []):
        packages.append(_source_package(item, category="dataset"))

    document_hash = sha256(json.dumps(packages, sort_keys=True).encode("utf-8")).hexdigest()[:16]
    return {
        "spdxVersion": SPDX_SCHEMA,
        "dataLicense": "CC0-1.0",
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": document_name,
        "documentNamespace": f"https://tryops.local/spdx/{document_name}-{document_hash}",
        "creationInfo": {
            "created": created_at,
            "creators": ["Tool: tryops-supply-chain-local"],
            "licenseListVersion": "3.25",
        },
        "packages": packages,
        "relationships": [
            {
                "spdxElementId": "SPDXRef-DOCUMENT",
                "relationshipType": "DESCRIBES",
                "relatedSpdxElement": package["SPDXID"],
            }
            for package in packages
        ],
    }


def detect_supply_chain_tools() -> dict[str, Any]:
    tools = {}
    for name in ["syft", "trivy", "grype", "pip-audit"]:
        path = shutil.which(name)
        tools[name] = {
            "available": path is not None,
            "path": path,
            "version": _tool_version(name, path) if path else None,
        }
    return tools


def build_local_vulnerability_scan(lock: dict[str, Any]) -> dict[str, Any]:
    alpha_versions = [
        {"name": entry["name"], "version": entry["locked_version"]}
        for entry in lock["dependencies"]
        if re.search(r"[abrc]\d", entry["locked_version"])
    ]
    lower_bound_pins = [
        {"name": entry["name"], "version": entry["locked_version"]}
        for entry in lock["dependencies"]
        if entry["lock_source"] == "pyproject_lower_bound"
    ]
    findings = []
    if alpha_versions:
        findings.append(
            {
                "id": "TRYOPS-SC-ALPHA-VERSION",
                "severity": "medium",
                "message": "One or more installed packages are pre-release versions.",
                "packages": alpha_versions,
            }
        )
    if lower_bound_pins:
        findings.append(
            {
                "id": "TRYOPS-SC-MISSING-INSTALLED-DIST",
                "severity": "info",
                "message": "Some direct dependencies are not installed locally; lock uses pyproject lower bounds.",
                "packages": lower_bound_pins,
            }
        )
    return {
        "schema_version": "tryops.local_supply_chain_scan.v1",
        "scanner": "tryops-local-hygiene",
        "scope": "direct dependency lock only; no CVE database matching",
        "findings": findings,
        "summary": {
            "total": len(findings),
            "critical": 0,
            "high": 0,
            "medium": sum(1 for item in findings if item["severity"] == "medium"),
            "info": sum(1 for item in findings if item["severity"] == "info"),
        },
    }


def write_supply_chain_report(
    *,
    pyproject_path: str | Path = Path("pyproject.toml"),
    model_sources_path: str | Path = Path("configs/model_sources.json"),
    dataset_licenses_path: str | Path = Path("configs/dataset_licenses.json"),
    requirements_output: str | Path = Path("requirements.lock"),
    output_path: str | Path = DEFAULT_SUPPLY_CHAIN_DIR / "supply_chain_report.json",
    sbom_output: str | Path = DEFAULT_SUPPLY_CHAIN_DIR / "sbom.spdx.json",
    dependency_lock_output: str | Path = DEFAULT_SUPPLY_CHAIN_DIR / "dependency_lock.json",
) -> dict[str, Any]:
    lock = write_dependency_lock(
        pyproject_path=pyproject_path,
        requirements_output=requirements_output,
        json_output=dependency_lock_output,
    )
    model_sources = load_model_sources(model_sources_path)
    dataset_licenses = load_dataset_licenses(dataset_licenses_path)
    model_audit = audit_model_sources(model_sources)
    dataset_audit = audit_dataset_licenses(dataset_licenses)
    sbom = build_spdx_sbom(lock=lock, model_sources=model_sources, dataset_licenses=dataset_licenses)
    sbom_path = Path(sbom_output)
    sbom_path.parent.mkdir(parents=True, exist_ok=True)
    sbom_path.write_text(json.dumps(sbom, indent=2, sort_keys=True), encoding="utf-8")

    tools = detect_supply_chain_tools()
    local_scan = build_local_vulnerability_scan(lock)
    external_scan = _external_scan_status(tools)
    report = {
        "schema_version": SUPPLY_CHAIN_SCHEMA,
        "created_at": datetime.now(UTC).isoformat(),
        "research_sources": {
            "syft": "https://github.com/anchore/syft",
            "trivy_filesystem": "https://trivy.dev/docs/latest/target/filesystem/",
            "spdx_2_3": "https://spdx.github.io/spdx-spec/v2.3/",
        },
        "artifacts": {
            "requirements_lock": str(requirements_output),
            "dependency_lock_json": str(dependency_lock_output),
            "sbom_spdx_json": str(sbom_output),
        },
        "tooling": tools,
        "dependency_lock": lock["audit"],
        "model_source_audit": model_audit,
        "dataset_license_audit": dataset_audit,
        "sbom": {
            "format": SPDX_SCHEMA,
            "package_count": len(sbom["packages"]),
            "document_namespace": sbom["documentNamespace"],
            "generated_by": "tryops fallback generator" if not tools["syft"]["available"] else "syft eligible",
        },
        "vulnerability_scan": external_scan,
        "local_hygiene_scan": local_scan,
        "passed": (
            lock["audit"]["passed"]
            and model_audit["passed"]
            and dataset_audit["passed"]
            and len(sbom["packages"]) >= 1 + len(lock["dependencies"])
        ),
    }
    output = Path(output_path)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    return report


def _lock_requirement(requirement: str, *, group: str) -> dict[str, Any]:
    match = REQUIREMENT_RE.match(str(requirement))
    if match is None:
        return {
            "group": group,
            "name": str(requirement),
            "requirement_name": str(requirement),
            "requirement": str(requirement),
            "locked_version": "",
            "lock_source": "parse_error",
            "installed": False,
            "extras": [],
        }
    name = _normalize_name(match.group(1))
    extras_text = match.group(2) or ""
    extras = [item.strip() for item in extras_text.strip("[]").split(",") if item.strip()]
    requirement_name = f"{name}[{','.join(extras)}]" if extras else name
    installed_version = _installed_version(name)
    lower_bound = _declared_version(str(requirement))
    locked_version = installed_version or lower_bound
    return {
        "group": group,
        "name": name,
        "requirement_name": requirement_name,
        "requirement": str(requirement),
        "locked_version": locked_version,
        "lock_source": "installed_distribution" if installed_version else "pyproject_lower_bound",
        "installed": installed_version is not None,
        "extras": extras,
    }


def _installed_version(name: str) -> str | None:
    try:
        return metadata.version(name)
    except metadata.PackageNotFoundError:
        return None


def _declared_version(requirement: str) -> str:
    match = VERSION_RE.search(requirement)
    return match.group(1) if match else ""


def _normalize_name(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def _spdx_id(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9.-]+", "-", value).strip("-")
    return f"SPDXRef-{cleaned or 'unknown'}"


def _project_package(lock: dict[str, Any]) -> dict[str, Any]:
    project = lock["project"]
    return {
        "name": project["name"] or "tryops",
        "SPDXID": "SPDXRef-Project-tryops",
        "versionInfo": project["version"] or "0.0.0",
        "downloadLocation": "NOASSERTION",
        "filesAnalyzed": False,
        "licenseConcluded": "Apache-2.0",
        "licenseDeclared": "Apache-2.0",
        "supplier": "Organization: TryOps contributors",
    }


def _dependency_package(entry: dict[str, Any]) -> dict[str, Any]:
    return {
        "name": entry["requirement_name"],
        "SPDXID": _spdx_id(f"Package-{entry['group']}-{entry['name']}"),
        "versionInfo": entry["locked_version"],
        "downloadLocation": "NOASSERTION",
        "filesAnalyzed": False,
        "licenseConcluded": "NOASSERTION",
        "licenseDeclared": "NOASSERTION",
        "externalRefs": [
            {
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": f"pkg:pypi/{entry['name']}@{entry['locked_version']}",
            }
        ],
    }


def _source_package(item: dict[str, Any], *, category: str) -> dict[str, Any]:
    version = str(item.get("revision", item.get("access_status", "unversioned")))
    license_name = str(item.get("license", "NOASSERTION"))
    return {
        "name": str(item.get("id", "unknown")),
        "SPDXID": _spdx_id(f"{category}-{item.get('id', 'unknown')}"),
        "versionInfo": version,
        "downloadLocation": str(item.get("source_uri", "NOASSERTION")),
        "filesAnalyzed": False,
        "licenseConcluded": license_name,
        "licenseDeclared": license_name,
        "comment": str(item.get("usage", item.get("allowed_use", ""))),
    }


def _missing_fields(items: list[dict[str, Any]], fields: list[str]) -> list[dict[str, str]]:
    missing = []
    for item in items:
        item_id = str(item.get("id", "unknown"))
        for field in fields:
            value = item.get(field)
            if value is None or value == "" or value == []:
                missing.append({"id": item_id, "field": field})
    return missing


def _tool_version(name: str, path: str | None) -> str | None:
    if path is None:
        return None
    command = [path, "--version"] if name in {"trivy", "pip-audit"} else [path, "version"]
    try:
        result = subprocess.run(command, check=False, capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return None
    return (result.stdout or result.stderr).strip().splitlines()[0] if (result.stdout or result.stderr).strip() else None


def _external_scan_status(tools: dict[str, Any]) -> dict[str, Any]:
    if tools["trivy"]["available"]:
        return {
            "status": "tool_available_not_executed_by_fallback",
            "preferred_command": "trivy fs --scanners vuln,secret,config,license --format json .",
            "reason": "This local report is generated without invoking external scanners automatically.",
        }
    return {
        "status": "tool_unavailable",
        "preferred_command": "trivy fs --scanners vuln,secret,config,license --format json .",
        "reason": "trivy is not installed in this workspace; local hygiene scan has no CVE database matching.",
    }
